import { Recycler, Lot, CollectorProfile, NotificationItem } from '../types';

export const SEEDED_COLLECTORS: CollectorProfile[] = [
  {
    id: 'COL-TN-101',
    name: 'Murugan Velusamy',
    phone: '+91 94441 87654',
    area: 'Guindy Industrial Area, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    language: 'en',
    simpleMode: false,
    voiceGuidedMode: false,
    voiceSpeed: 0.9,
    largeText: false,
    highContrast: false,
    isLoggedIn: true,
  },
  {
    id: 'COL-TN-102',
    name: 'K. Rajendran',
    phone: '+91 98402 12345',
    area: 'Velachery Bypass, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    language: 'ta',
    simpleMode: false,
    voiceGuidedMode: true,
    voiceSpeed: 0.9,
    largeText: false,
    highContrast: false,
    isLoggedIn: false,
  },
  {
    id: 'COL-TN-103',
    name: 'Lakshmi Narayanan',
    phone: '+91 94432 99881',
    area: 'Gandhipuram, Coimbatore',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    language: 'ta',
    simpleMode: false,
    voiceGuidedMode: false,
    voiceSpeed: 0.9,
    largeText: false,
    highContrast: false,
    isLoggedIn: false,
  },
  {
    id: 'COL-TN-104',
    name: 'S. Muthukumar',
    phone: '+91 97901 34567',
    area: 'Simmakkal Market, Madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    language: 'ta',
    simpleMode: true,
    voiceGuidedMode: true,
    voiceSpeed: 0.9,
    largeText: false,
    highContrast: false,
    isLoggedIn: false,
  }
];

export const SEEDED_RECYCLERS: Recycler[] = [
  {
    id: 'REC-TN-01',
    name: 'Murugan Swaminathan (Yard Head)',
    businessName: 'CHENNAI GREEN CYCLE',
    isVerified: true,
    isDemoRecycler: true,
    licenseNumber: 'TNPCB/E-WASTE/CHN/2026/041',
    rating: 4.9,
    phone: '+91 98400 11223',
    location: 'Ambattur Industrial Estate, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    distanceKm: 3.2,
    acceptedMaterials: ['E-waste', 'Plastic', 'Metal'],
    priceRangePerKg: {
      'E-waste': [280, 340],
      'Plastic': [40, 70],
      'Metal': [90, 130],
    },
    pickupAvailable: true,
    pickupTimeline: 'Available Today',
    paymentMethods: ['UPI', 'Cash', 'Bank Transfer'],
    capacityPerDayKg: 8000,
  },
  {
    id: 'REC-TN-02',
    name: 'K. Selvam (Intake Manager)',
    businessName: 'TAMIL ECO RECYCLING',
    isVerified: true,
    isDemoRecycler: true,
    licenseNumber: 'TNPCB/CIRCULAR-PLAST/2025/119',
    rating: 4.8,
    phone: '+91 98411 44332',
    location: 'Guindy Thiru-Vi-Ka Estate, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    distanceKm: 5.1,
    acceptedMaterials: ['E-waste', 'Plastic'],
    priceRangePerKg: {
      'E-waste': [275, 335],
      'Plastic': [42, 68],
    },
    pickupAvailable: true,
    pickupTimeline: 'Tomorrow',
    paymentMethods: ['UPI', 'Cash'],
    capacityPerDayKg: 6500,
  },
  {
    id: 'REC-TN-03',
    name: 'P. Anbarasan',
    businessName: 'SOUTH CIRCULAR RECYCLING',
    isVerified: true,
    isDemoRecycler: true,
    licenseNumber: 'CPCB/HW-RECOVERY/CHN/9102',
    rating: 4.8,
    phone: '+91 97899 77881',
    location: 'Madhavaram Scrap Corridor, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    distanceKm: 7.4,
    acceptedMaterials: ['Metal', 'Plastic', 'E-waste'],
    priceRangePerKg: {
      'Metal': [92, 135],
      'Plastic': [45, 72],
      'E-waste': [290, 345],
    },
    pickupAvailable: true,
    pickupTimeline: 'Available Today',
    paymentMethods: ['UPI', 'Cash', 'Bank Transfer'],
    capacityPerDayKg: 15000,
  },
  {
    id: 'REC-TN-04',
    name: 'V. Senthilkumar',
    businessName: 'MADRAS METALS & E-RECLAIM',
    isVerified: true,
    isDemoRecycler: true,
    licenseNumber: 'TNPCB/EPR-REFINER/2026/088',
    rating: 4.7,
    phone: '+91 94440 55667',
    location: 'Manali Petrochemical Corridor, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    distanceKm: 9.1,
    acceptedMaterials: ['E-waste', 'Metal'],
    priceRangePerKg: {
      'E-waste': [285, 340],
      'Metal': [95, 130],
    },
    pickupAvailable: true,
    pickupTimeline: 'Scheduled in 24 hrs',
    paymentMethods: ['UPI', 'Cash'],
    capacityPerDayKg: 10000,
  },
  {
    id: 'REC-TN-05',
    name: 'A. Ramanathan',
    businessName: 'KOVAI GREEN RECLAMATION',
    isVerified: true,
    isDemoRecycler: true,
    licenseNumber: 'TNPCB/REG-CBE/2025/302',
    rating: 4.9,
    phone: '+91 94430 22119',
    location: 'SIDCO Industrial Estate, Kurichi, Coimbatore',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    distanceKm: 4.2,
    acceptedMaterials: ['E-waste', 'Metal', 'Plastic'],
    priceRangePerKg: {
      'E-waste': [280, 335],
      'Metal': [88, 128],
      'Plastic': [40, 68],
    },
    pickupAvailable: true,
    pickupTimeline: 'Available Today',
    paymentMethods: ['UPI', 'Cash'],
    capacityPerDayKg: 9000,
  },
  {
    id: 'REC-TN-06',
    name: 'T. Karuppasamy',
    businessName: 'MADURAI CIRCULAR RECYCLERS',
    isVerified: true,
    isDemoRecycler: true,
    licenseNumber: 'TNPCB/MDU-HW/2026/112',
    rating: 4.7,
    phone: '+91 98421 88776',
    location: 'Kappalur Industrial Area, Madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    distanceKm: 3.8,
    acceptedMaterials: ['E-waste', 'Plastic', 'Metal', 'Paper'],
    priceRangePerKg: {
      'E-waste': [275, 330],
      'Plastic': [38, 65],
      'Metal': [85, 125],
      'Paper': [16, 24],
    },
    pickupAvailable: true,
    pickupTimeline: 'Tomorrow',
    paymentMethods: ['UPI', 'Cash'],
    capacityPerDayKg: 7500,
  }
];

export const INITIAL_LOTS: Lot[] = [
  {
    id: 'KC-CHN-2026-00108',
    collectorId: 'COL-TN-101',
    collectorName: 'Murugan Velusamy',
    collectorPhone: '+91 94441 87654',
    collectorArea: 'Guindy Industrial Area, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    material: 'E-waste',
    subCategory: 'Mobile PCBs and SMPS adapters',
    weightKg: 8.5,
    photoUrl: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
    aiDetected: 'Printed Circuit Boards (Grade A/B Components)',
    aiConfidence: 89,
    alternativeOptions: ['Computer motherboards', 'Power supplies', 'Mixed telecom scrap'],
    estimatedPriceMin: 2380,
    estimatedPriceMax: 2890,
    finalPricePerKg: 330,
    totalAmount: 2805,
    recyclerId: 'REC-TN-01',
    recyclerName: 'CHENNAI GREEN CYCLE',
    status: 'PAID',
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    isOfflineCreated: false,
    syncStatus: 'Synced',
    createdAt: '2026-02-28, 10:15 AM',
    qrPayload: 'KC-CHN-2026-00108|E-WASTE|8.5KG|PAID|UPI-981729381',
    timeline: [
      { status: 'CREATED', stageName: 'COLLECTED', timestamp: '10:15 AM', date: '28 Feb 2026', note: 'Lot logged via Android App with AI Camera Vision', actor: 'Collector (Murugan)', verified: true, locationStamp: '13.0067° N, 80.2021° E (Guindy Ward, Chennai)', syncStatus: 'Synced' },
      { status: 'CREATED', stageName: 'AI_IDENTIFIED', timestamp: '10:16 AM', date: '28 Feb 2026', note: 'AI classified Grade A/B circuit scrap (89% confidence)', actor: 'AI Edge Engine', verified: true, syncStatus: 'Synced' },
      { status: 'CREATED', stageName: 'PRICE_ESTIMATED', timestamp: '10:17 AM', date: '28 Feb 2026', note: 'Indicative Chennai mandi rate estimated: ₹280-₹340/kg', actor: 'Pricing Service', verified: true, syncStatus: 'Synced' },
      { status: 'RECYCLER_ACCEPTED', stageName: 'RECYCLER_SELECTED', timestamp: '10:30 AM', date: '28 Feb 2026', note: 'Rate approved at ₹330/kg by Chennai Green Cycle Yard', actor: 'Recycler (Chennai Green Cycle)', verified: true, syncStatus: 'Synced' },
      { status: 'PICKUP_SCHEDULED', stageName: 'PICKUP', timestamp: '11:00 AM', date: '28 Feb 2026', note: 'Driver dispatched on Tata Ace TN-09-AB-4321', actor: 'Logistics Fleet', verified: true, syncStatus: 'Synced' },
      { status: 'HANDED_OVER', stageName: 'HANDOVER', timestamp: '01:00 PM', date: '28 Feb 2026', note: 'Doorstep scale reading verified: 8.50 kg. Handover signed.', actor: 'Collector & Logistics Driver', verified: true, locationStamp: '13.0067° N, 80.2021° E', hashSignature: '0x8f2d...91c4', syncStatus: 'Synced' },
      { status: 'PAID', stageName: 'PAYMENT', timestamp: '01:05 PM', date: '28 Feb 2026', note: 'Instant UPI payout transferred. Ref: UPI/SBI/981729381', actor: 'Automated Escrow Desk', verified: true, hashSignature: '0x9a3e...b411', syncStatus: 'Synced' },
      { status: 'PAID', stageName: 'FORMAL_RECYCLING', timestamp: '03:30 PM', date: '28 Feb 2026', note: 'Material batched into CPCB-certified hydrometallurgical recovery line', actor: 'Yard Operations', verified: true, hashSignature: '0x4c1a...77e9', syncStatus: 'Synced' }
    ]
  },
  {
    id: 'KC-CHN-2026-00124',
    collectorId: 'COL-TN-101',
    collectorName: 'Murugan Velusamy',
    collectorPhone: '+91 94441 87654',
    collectorArea: 'Guindy Industrial Area, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    material: 'E-waste',
    subCategory: 'Mixed Electronic Scrap',
    weightKg: 12.0,
    photoUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=600&q=80',
    aiDetected: 'Mixed Electronic Scrap (Computer parts, adapters, telecom cables)',
    aiConfidence: 87,
    alternativeOptions: ['Desktop computer parts', 'Household appliances', 'Power cables & wiring'],
    estimatedPriceMin: 3360,
    estimatedPriceMax: 4080,
    finalPricePerKg: 330,
    totalAmount: 3960,
    recyclerId: 'REC-TN-01',
    recyclerName: 'CHENNAI GREEN CYCLE',
    status: 'PICKUP_SCHEDULED',
    paymentMethod: 'UPI',
    paymentStatus: 'PENDING',
    isOfflineCreated: false,
    syncStatus: 'Synced',
    createdAt: '2026-03-01, 08:30 AM',
    qrPayload: 'KC-CHN-2026-00124|E-WASTE|12KG|PICKUP_SCHEDULED|REC-TN-01',
    timeline: [
      { status: 'CREATED', stageName: 'COLLECTED', timestamp: '08:30 AM', date: '01 Mar 2026', note: 'Scrap lot registered with AI Assistance in Chennai Pilot', actor: 'Collector (Murugan)', verified: true, locationStamp: '13.0067° N, 80.2021° E', syncStatus: 'Synced' },
      { status: 'CREATED', stageName: 'AI_IDENTIFIED', timestamp: '08:31 AM', date: '01 Mar 2026', note: 'Edge AI detected Mixed E-waste with 87% confidence', actor: 'AI Edge Engine', verified: true, syncStatus: 'Synced' },
      { status: 'CREATED', stageName: 'PRICE_ESTIMATED', timestamp: '08:32 AM', date: '01 Mar 2026', note: 'Indicative Chennai price range: ₹280–₹340/kg', actor: 'Pricing Engine', verified: true, syncStatus: 'Synced' },
      { status: 'RECYCLER_ACCEPTED', stageName: 'RECYCLER_SELECTED', timestamp: '09:00 AM', date: '01 Mar 2026', note: 'Rate approved ₹330/kg by Chennai Green Cycle', actor: 'Chennai Green Cycle Dispatch', verified: true, syncStatus: 'Synced' },
      { status: 'PICKUP_SCHEDULED', stageName: 'PICKUP', timestamp: '09:45 AM', date: '01 Mar 2026', note: 'Electric pickup van arriving today between 3:00 PM – 4:00 PM', actor: 'Logistics Fleet', verified: true, syncStatus: 'Synced' }
    ]
  },
  {
    id: 'KC-CHN-2026-00130',
    collectorId: 'COL-TN-101',
    collectorName: 'Murugan Velusamy',
    collectorPhone: '+91 94441 87654',
    collectorArea: 'Guindy Industrial Area, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    material: 'Plastic',
    subCategory: 'HDPE Rigid Milk & Oil Containers',
    weightKg: 25.0,
    photoUrl: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=600&q=80',
    aiDetected: 'High-Density Polyethylene (HDPE - Resin Code 2)',
    aiConfidence: 94,
    alternativeOptions: ['PET bottles', 'PP polypropylene buckets', 'Mixed film plastic'],
    estimatedPriceMin: 1000,
    estimatedPriceMax: 1750,
    status: 'CREATED',
    paymentStatus: 'PENDING',
    isOfflineCreated: false,
    syncStatus: 'Synced',
    createdAt: '2026-03-01, 11:20 AM',
    qrPayload: 'KC-CHN-2026-00130|PLASTIC|25KG|CREATED',
    timeline: [
      { status: 'CREATED', stageName: 'COLLECTED', timestamp: '11:20 AM', date: '01 Mar 2026', note: 'Lot created and published to verified Tamil Nadu plastic recyclers', actor: 'Collector (Murugan)', verified: true, locationStamp: '13.0067° N, 80.2021° E', syncStatus: 'Synced' }
    ]
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    title: 'Recycler Rate Accepted',
    message: 'Chennai Green Cycle approved ₹330/kg for your 12 kg E-waste Lot #KC-CHN-2026-00124.',
    timestamp: '09:00 AM',
    type: 'accept',
    read: false,
    lotId: 'KC-CHN-2026-00124',
  },
  {
    id: 'NOTIF-2',
    title: 'Pickup Van Scheduled',
    message: 'Tata Ace (TN-09-AB-4321) scheduled for Guindy Industrial Area by 3:30 PM.',
    timestamp: '09:45 AM',
    type: 'pickup',
    read: false,
    lotId: 'KC-CHN-2026-00124',
  },
  {
    id: 'NOTIF-3',
    title: 'Instant Payment Settled (₹2,805)',
    message: '₹2,805 credited via UPI for Lot #KC-CHN-2026-00108. Digital invoice generated.',
    timestamp: 'Yesterday',
    type: 'payment',
    read: true,
    lotId: 'KC-CHN-2026-00108',
  }
];

export const OFFLINE_PRICE_BASELINES: Record<string, { min: number; max: number; unit: string; description: string }> = {
  'E-waste': {
    min: 280,
    max: 340,
    unit: '₹/kg',
    description: 'Mixed electronic scrap, printed circuit boards, SMPS power supplies, computer peripherals'
  },
  'Plastic': {
    min: 40,
    max: 70,
    unit: '₹/kg',
    description: 'Rigid HDPE bottles, PET clear flakes, PP injection grade drums'
  },
  'Metal': {
    min: 90,
    max: 130,
    unit: '₹/kg',
    description: 'Copper cables, aluminum extrusions, brass fittings, mixed iron scrap'
  },
  'Paper': {
    min: 15,
    max: 25,
    unit: '₹/kg',
    description: 'Corrugated cartons, sorted white office paper, newsprint bundles'
  }
};
